### ISSUE TITLE
[Feature / CSS tweak] Make the comment collapse button easier to tap/click

### ISSUE THREAD

**Issue by sudoshindo** [OctoNezd/oldlander#150] opened 2024-05-15 21:42 UTC
**Is your feature request related to a problem? Please describe.**

Yes. My problem is that the touch target for collapsing comments is hard to hit.

I still hit the username often.

**Describe the solution you'd like**

Just adjust the CSS slightly so that the comment collapse button is wider/bigger.

Also increase the margin between the collapse button and username.

**Describe alternatives you've considered**

x

**Additional context**

x

___

Is Expando the term I'm supposed to call the collapse buttons?

**Comment by OctoNezd** [comment] 2024-05-16 07:16
Duplicate of #110 

I hope I will fix it soon enough, but I dont really have much free time

**Closed by OctoNezd** 2024-05-16 07:16 UTC
