### ISSUE TITLE
More UI customization ability for users + minimalist UI tweaks

### ISSUE THREAD

**Issue by aswinnnn** [OctoNezd/oldlander#126] opened 2024-03-22 04:12 UTC
Currently, the "post options" buttons take up a lot more space than they should.
![](https://cdn.discordapp.com/attachments/715473848925028482/1220582865134424094/IMG_20240322_092623.jpg?ex=660f7760&is=65fd0260&hm=c6e0b736a3a48afb4d8cc99416315985753900aff779ed5e0cda2abbbe7fc54c&)

I think the buttons are fine on their own, and the font size is upto the users, but when you have 20 or more posts in a row just like this, its just a bit unsightly is all.

Number of ways to approach this:

- Make them collapse: Have an > button or something that could show the extra buttons (everything other than votes and comment) when the user wants them to.

- Touch Events: Keep the up/down votes and comment button, rest of the options appear when the user holds over a post.

- Just something in the preference: An ability to choose what buttons to show or hide would be extremely useful.

I like what you've done and hope youre not offended by my stylistic choices lol. I think the users should focus on the post more than the buttons. Let me know if i can help.

**Comment by OctoNezd** [comment] 2024-03-22 08:50
Yes, I plan on doing that - move all options except for comments and votes under 3-dot menu.

Duplicate of #101

**Closed by OctoNezd** 2024-03-22 08:50 UTC
